spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

    hibernate:
      ddl-auto: create-drop

    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: off
        type: trace